name: 🐛 Bug Report
description: Report a problem or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Environment details
      description: OS, browser, version, etc.
