name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
      description: Explain the motivation behind the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the proposed solution
  - type: textarea
    attributes:
      label: Additional context or screenshots
